my_diffbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # # Position Controllers ---------------------------------------
  # joint1_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: left_wheel_joint
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
  # joint2_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: right_wheel_joint
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  # Velocity Controllers ---------------------------------------
  leftWheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_wheel_joint
    pid: {p: 5.0, i: 20.0, d: 0.0}
  rightWheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_wheel_joint
    pid: {p: 5.0, i: 20.0, d: 0.0}